# Render deployment configuration
services:
  - type: staticSite
    name: corknote
    repo: https://github.com/SuperB747/corknote
    branch: main
    buildCommand: npm install --prefix client && npm run build --prefix client
    publishPath: client/build
    envVars:
      - key: REACT_APP_FIREBASE_API_KEY
        value: YOUR_FIREBASE_API_KEY
      - key: REACT_APP_FIREBASE_AUTH_DOMAIN
        value: YOUR_FIREBASE_AUTH_DOMAIN
      - key: REACT_APP_FIREBASE_PROJECT_ID
        value: YOUR_FIREBASE_PROJECT_ID
      - key: REACT_APP_FIREBASE_STORAGE_BUCKET
        value: YOUR_FIREBASE_STORAGE_BUCKET
      - key: REACT_APP_FIREBASE_MESSAGING_SENDER_ID
        value: YOUR_FIREBASE_MESSAGING_SENDER_ID
      - key: REACT_APP_FIREBASE_APP_ID
        value: YOUR_FIREBASE_APP_ID 